version: "3.8"

services:
  web:
    image: gbacentrotecnico/sistema-bi:latest
    container_name: bi_web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - DOMAIN=${DOMAIN}
    restart: always
    networks:
      - network_swarm_public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.sistema_bi.rule=Host(`relatorios.gbamecanica.com.br`)"
        - "traefik.http.routers.sistema_bi.entrypoints=websecure"
        - "traefik.http.routers.sistema_bi.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.sistema_bi.loadbalancer.server.port=3000"

  worker:
    image: gbacentrotecnico/sistema-bi:latest
    container_name: bi_worker
    command: npm run worker
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - DOMAIN=${DOMAIN}
    restart: always
    networks:
      - network_swarm_public

networks:
  network_swarm_public:
    external: true

